{% set name = "hydrosar" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hydrosar-{{ version }}.tar.gz
  sha256: 8ef6627e8924dbf590449dd9f510d04a30750246bebb69bae2367368d7cfbf17

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - calculate_hand = hydrosar.hand.calculate:main
    - make_FD30 = hydrosar.flood_map:main
    - make_HYDRO30 = hydrosar.water_map:main

requirements:
  host:
    - python >=3.8
    - pip
    - python-build
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >=3.8
    - asf_tools >=0.6
    - astropy
    - fiona
    - gdal >=3.3
    - numpy
    - pysheds >=0.3
    - rasterio
    - scikit-fuzzy
    - scikit-image
    - scipy
    - shapely
    - tqdm

test:
  imports:
    - hydrosar
  commands:
    - pip check
    - calculate_hand --help
    - make_FD30 --help
    - make_HYDRO30 --help
  requires:
    - pip

about:
  home: https://github.com/HydroSAR/HydroSAR
  summary: Algorithms for the monitoring of hydrological hazards using data from Synthetic Aperture Radar (SAR) sensors
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhkennedy
